### ISSUE TITLE
`useDrag` can get stuck in "down" state

### ISSUE THREAD

**Issue by timoxley** [pmndrs/use-gesture#376] opened 2021-10-28 16:06 UTC
It seems possible to get stuck in a state where `down` is always `true`, this seems to happen (sometimes) under certain conditions:
* mouse button (trackpad) is currently down
* window is resized while dragging (e.g. via keyboard shortcut)
* mousebutton is clicked/released outside the window

**Edit:** Doesn't even need resize, just releasing the mouse while outside the drag element seems to be enough: https://github.com/pmndrs/use-gesture/issues/376#issuecomment-955688757

This may seem somewhat of an edge case, but I keep accidentally hitting this while developing and it's very annoying. 
It doesn't happen every time, I had to do a few takes to capture the problem. It might be timing related. I think I've seen it also happen without a resize, just by releasing the mouse while not over the window, but I may be mistaken, I couldn't reproduce for the screencap. I just know this kept happening to me every few minutes while I was developing, and I don't believe I was resizing windows while the mouse is down that frequently.

The underlying issue seems to be that the code assumes a `pointerup` event will always be fired when the mouse button is released, but there's at least one circumstance (described above) where this assumption doesn't hold.

https://github.com/pmndrs/use-gesture/blob/5b9715c869c2945c8d34178453fcfad11ecc48d9/packages/core/src/engines/Engine.ts#L211-L214

https://github.com/pmndrs/use-gesture/blob/5b9715c869c2945c8d34178453fcfad11ecc48d9/packages/core/src/Controller.ts#L40-L51

**Sandbox or Video**

https://user-images.githubusercontent.com/43438/139291136-4c1657d9-12e6-4ae0-b55e-a5aabbc90827.mp4

https://codesandbox.io/s/amazing-poincare-6bv0l?file=/src/index.tsx

**Information:**
 - React Use Gesture version: 10.1.1
 - Device: Macbook Pro 2019
 - OS: MacOS 12.0.1 
 - Browser: Chrome 95.0.4638.54

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).

**Comment by timoxley** [comment] 2021-10-31 12:14
Oh ugh, yeah you can get this same bug just by moving the cursor too fast and releasing the mouse, no resize necessary. See example below from the docs:

https://user-images.githubusercontent.com/43438/139582269-c03e63fb-65fd-4132-9fe6-a696ab76111c.mp4

In this case, the onDrag event handler doesn't actually fire again until the cursor hovers over the drag target again.

So there appears to be two bugs:
* event handler stops firing if pointer is released too quickly after cursor leaves the drag target
* event handler can fire with incorrect down state

By adding a pointermove event to the window, and checking for button state in there, it could be possible to implement a workaround, but as far as I can tell there's no way to cancel the drag outside of an onDrag event handler, and if the onDrag handler isn't firing then there's no way to cancel the drag. I guess one could capture the cancel function from a previous drag, but yeah.

**Comment by dbismut** [comment] 2021-10-31 14:50
@timoxley I can't reproduce. I believe this is not about the mouse moving too fast, but maybe your screen recording app coming on the foreground while dragging. This lib has a lot of options, but in its simplest form, it relies on core web API.

- when pointer is pressed, the dragged target captures the event pointer id. This means that all pointer events from now on will propagate to the element target, whether the pointer is actually over the target or not.
- when the pointer is released, the target releases the capture of the event pointer id (note that this doesn't seem to be strictly necessary, it seems that releasing the pointer automatically releases its capture.

And that's the end of the story.

The bug about `down` not being reflective of the actual state of the pointer happens when the pointer is released when the browser app is not in the foreground, since — except for Safari —, the browser doesn't catch the `pointerup` event.

**Comment by timoxley** [comment] 2021-10-31 16:09
@dbismut I'll see if I can whip up a sandbox but note the only reason I started recording was because I was seeing the issue, so it can't be something specific to the screen recording behaviour.

**Comment by dbismut** [comment] 2021-10-31 16:36
Could be command-tab app switching, back and forth. This would be a weird bug if this was indeed about the mouse speed.

**Comment by timoxley** [comment] 2021-10-31 17:07
@dbismut What OS/Browser are you on? Can you try again with CPU throttling enabled in DevTools?
![image](https://user-images.githubusercontent.com/43438/139593800-59c7d9e5-9ef4-4b3c-9708-403d4f1aebab.png)

With CPU throttling enabled I'm able to get it to happen almost every time using the first demo on https://use-gesture.netlify.app/docs/state/ 

No screen recording, no cmd-tabbing, no resizing windows. Just fast movement.

I'm in Chrome 95 on Mac. Couldn't repro on the docs page in Safari or Firefox, but also didn't see a way to CPU throttle them via devtools. Tried running the screencap software and also running devtools profiling to try slow things down but it didn't seem to work. It's possible the bug is something Chrome. The actual app I noticed this is in react-three/fiber, so it's possible the issue is caused by a performance drop due to pushing webgl too hard.

**Comment by dbismut** [comment] 2021-10-31 17:16
MBA M1, Mac OS 12.0.1, Chrome 95, using the trackpad. Already had set CPU throttling to x6, can't reproduce I'm sorry... I'm happy to get in touch on [Discord](https://discord.gg/poimandres) if you'd like, so we can at least isolate that issue!

**Comment by Emiliano-Bucci** [comment] 2021-12-06 15:40
@dbismut Hi! If this can somehow help, i also get the down state always as true (as well as pressed=true) when i assign `pan-y` to the container and then i drag vertically. Somehow, those values get stucked and aren't cleared again. 

Hope can helps!

**Comment by dbismut** [comment] 2021-12-06 15:57
@Emiliano-Bucci that's super helpful indeed. Makes sense now. I'll try to see how I can fix this.

**Closed** 2021-12-06 16:12 UTC

**Comment by dbismut** [comment] 2021-12-06 16:13
Let me know if this happens to be fixed in `10.2.1`!

**Comment by docduo** [comment] 2021-12-25 22:28
No, I can reproduce this issue in the latest version @dbismut

**Comment by docduo** [comment] 2021-12-26 17:48
If this can help, I can only reduce the issue (which is very annoying because it's on Chrome, so it's represent a lot of users), using the macbook trackpad. I have an additionnal logitech mouse and I can not reproduce the issue with the mouse.

**Comment by megabuz** [comment] 2022-01-02 22:35
I see the same issue on chrome with MacBook trackpad. It does not reproduce constantly, but when it does `pointerup` event is not caught and it can be logged in an outer element.

**Comment by dbismut** [comment] 2022-01-02 22:52
@megabuz I'm not sure I understand the last bit, can you elaborate?

**Comment by megabuz** [comment] 2022-01-02 23:27
Sorry for the confusion.
In the structure similar to
```
<div onPointerUp={(event) => {console.log(event)}}>
<div {...bindDrag()} />
</div>
```
Console log will be triggered if drag is stuck in "down" state. In case if drag works fine, log will not be fired

**Comment by dbismut** [comment] 2022-01-02 23:30
Thanks for clarifying. Is there a way to get Chrome stuck in down true mode somehow?

**Comment by megabuz** [comment] 2022-01-03 13:28
I didn't find the way to constantly reproduce it. It looks like in some random occasions `pointerup` event is not handled properly, but I can't see why.

**Comment by timoxley** [comment] 2022-01-03 13:37
@dbismut maybe worth reopening this issue?

**Comment by megabuz** [comment] 2022-01-16 16:23
I did a small research of my case.
I have a bunch of draggable elements on the page, specifically there is a container, that has useDrag handler and elements in the container also using useDrag.

Anyway when I move elements, sometimes they loose pointer capture. So I receive `lostpointercapture` in element drag handler and `pointerUp` after that goes to my container drag handler.

I do not know why my elements loose pointer capture, but this is the reason of my problems

**Comment by yeefun** [comment] 2022-03-02 19:48
@dbismut I have the similar issue, but it's hard to reproduce. Could you expose an option `pointer.mouse` like `pointer.touch`? If we find the pointer events have some problems, we can choose to use the mouse events.

**Comment by jkorzeniewski380** [comment] 2022-12-21 16:05
Does anyone else still have this issue? My project uses `@use-gesture/react: "^10.2.23"` and if I move out of the dragged element and quickly release the mouse button, the 'down' state is set to true & 'last' is always false. The last recorded event is of `pointermove` type. Is there any workaround?

**Comment by samcarton** [comment] 2023-07-19 07:01
Did anyone find a workaround for this? still seems to be an issue in version `10.2.27`.
Very easy to reproduce on an M1 MacBook Air trackpad (Chrome 115), just on the first example on the docs page. Seems to work fine on my windows desktop though (also Chrome 115).

**Comment by samcarton** [comment] 2023-07-20 03:45
It looks like the `down` state in particular is causing the issue. If you can manage to make use of the `active` state exclusively, then it should function as expected. Example codesandbox https://codesandbox.io/s/laughing-matsumoto-vlsfx5?file=/src/App.tsx  

This is from console logging both `active` and `down` when swiping on the MacBook trackpad:
![image](https://github.com/pmndrs/use-gesture/assets/1586059/285a5f09-babb-42c1-9978-54e7f2ed7441)
While `down` gets stuck in `true`, `active` seems to correctly get set to `false`. So if you control element\spring position based on `active` it wont get stuck.

**Comment by tanishqk-shortwave** [comment] 2023-07-25 20:51
This issue still happens today. There is a workaround by passing a config option to set pointer capture to false and forcing it to use mouse events instead:
```tsx
useDrag(..., { pointer: { capture: false } })
```
Hope that helps :)

**Comment by oliwheeler** [comment] 2023-09-28 07:54
I can reproduce this issue intermittently on the [Simple react example](https://use-gesture.netlify.app/docs/#simple-react-example).
The issue never occurs for me on the [Simple Vanilla example](https://use-gesture.netlify.app/docs/#simple-vanilla-example)

Device: Macbook Pro 16" 2019 (Chrome 117)


https://github.com/pmndrs/use-gesture/assets/10214164/f09b1262-7ed7-4d1d-9795-7034fe2cd054
