### ISSUE TITLE
[Suggestion] Long Press gesture

### ISSUE THREAD

**Issue by ajaypillay** [pmndrs/use-gesture#303] opened 2021-05-21 09:50 UTC
Hi, I was just wondering if this library could include a hook to detect a long press/long touch. Similar to how this [useLongPress](https://stackoverflow.com/questions/48048957/react-long-press-event) hook works as given in the first answer.

This would be useful in many examples where you want to detect a long press instead of just a drag. The reason would be because this may interfere with the browser's scrolling, and you want the user to be able to scroll without dragging the components around, so they can only interact with components after a long press.

Would this be a good thing to include, or are there other ways to achieve this same functionality?

Thanks!

**Comment by dbismut** [comment] 2021-05-21 09:51
Duplicate of #241

**Closed by dbismut** 2021-05-21 09:51 UTC

**Comment by dbismut** [comment] 2021-05-21 09:57
Btw the preventScroll functionality tackles the usecase you're mentioning. See v10 docs in #300

**Comment by ajaypillay** [comment] 2021-05-21 11:00
> Duplicate of #241

Oh sorry I missed that! I only searched closed issues, my bad.

> Btw the preventScroll functionality tackles the usecase you're mentioning. See v10 docs in #300

And alright, thank you! I will try that out.

**Comment by ajaypillay** [comment] 2021-05-21 12:45
> Btw the preventScroll functionality tackles the usecase you're mentioning. See v10 docs in #300

Hi @dbismut, so I tried out the demo in the docs on mobile.

https://user-images.githubusercontent.com/917752/119138870-f2f44700-ba74-11eb-99db-f82e599a65cd.mp4

I understand that in the docs it's stated that it's not working perfectly on mobile yet, is this the issue?

**Comment by dbismut** [comment] 2021-05-21 13:42
That's weird as it works on my iPhone. The text selection is a bummer though, I get that as well: I think it's unrelated to the lib but long press on the screen always triggers some selection: one way to make it go for sure is to disable user-selection on the whole page but I need to investigate that more.

Anyway: what device are you using? Did you try on Chrome Responsive Mode? Btw I think the first touch that doesn't work is because you're somehow clicking through the torus (inside one of its holes).

There's another sandbox that shows it, let me know if it behaves differently.
https://codesandbox.io/s/github/pmndrs/use-gesture/tree/v10/demo/src/sandboxes/draggable-list-prevent-scroll

**Comment by ajaypillay** [comment] 2021-05-21 14:10
> Anyway: what device are you using? Did you try on Chrome Responsive Mode? Btw I think the first touch that doesn't work is because you're somehow clicking through the torus (inside one of its holes).

Oh yes you're right, it was going through the torus. It's odd because the click registered since the torus enlarged, but subsequently was lost as it was probably detected to be within the holes. I tried it out at a few different points and it works, but I have to be very careful where I start the touch event. I'm running Android 11 on a Pixel 3 XL, Chrome version 90.0.4430.210.

> There's another sandbox that shows it, let me know if it behaves differently.
> https://codesandbox.io/s/github/pmndrs/use-gesture/tree/v10/demo/src/sandboxes/draggable-list-prevent-scroll

Yes this works too, without any text highlighting. All of this was in normal mode, not Chrome Responsive Mode.

**Comment by dbismut** [comment] 2021-05-21 14:41
When you say normal mode, you mean your phone or the desktop browser with mouse?

**Comment by ajaypillay** [comment] 2021-05-21 14:51
> When you say normal mode, you mean your phone or the desktop browser with mouse?

By normal mode I mean on my phone. On desktop there shouldn't be any difference right? There isn't any click-and-hold 250ms delay, so it works the same as it did before v10.

**Comment by dbismut** [comment] 2021-05-21 15:23
Thanks! Indeed desktop mode doesn't need any delay. So the one thing that doesn't work is the canvas with the torus right? Interesting 😆

**Comment by ajaypillay** [comment] 2021-05-21 15:28
Yes, due to the text highlighting.

**Comment by ajaypillay** [comment] 2021-05-25 21:33
Hi @dbismut I just tested it out and it works great, however I was wondering what is the expectation regarding preventing horizontal scrolling? I have a component I need which only scrolls horizontally and thus I need a delay there.

Also - what about configuring the time delay instead of a fixed 250ms?

Thanks.

**Comment by dbismut** [comment] 2021-05-25 21:37
Preventing horizontal scrolling isn't supported at this point, but the 250ms delay would be pretty easy to add (preventScroll would then be either a boolean or a duration). You can submit a PR if you're up to it.

**Comment by ajaypillay** [comment] 2021-05-25 21:40
I see, interesting. With regards to preventing horizontal scrolling, are there any problems of some sort which have prevented it from being implemented in the same way as vertical scrolling? I'll try to explore this more.

**Comment by dbismut** [comment] 2021-05-25 22:24
No absolutely not. If you want to discuss on Discord about this I can explain where the logic is, it think it should be an easy upgrade. Please refer to the v10 branch as the main branch is soon to be outdated.

**Comment by ajaypillay** [comment] 2021-05-26 10:40
I have created a PR for adding a duration for preventScroll. I have some other things to work on right now but I might have a go at the horizontal scroll as well soon. I will contact you on Discord if I have any questions. Thanks for maintaining this excellent package!
