### ISSUE TITLE
onDrag stops firing when cursor gets out of targets bounds

### ISSUE THREAD

**Issue by natarius** [pmndrs/use-gesture#334] opened 2021-07-14 04:39 UTC
**Describe the bug**
I am using useGesture to drag ThreeJS Fiber groups an am running into a issue where as soon as the mouse cursors leaves the bounds of the dragged object the onDrag event stops firing (see video)

Any idea whats going on?

Here is my code

```
const {gl} = useThree();

const [spring, setSpring] = useSpring(() => ({position: [position.x, position.y, position.z], scale: [1, 1, 1]}));

const bind = useGesture(
        {
            onDragStart: (state) => {
                if (state.event.buttons === 1) {
                    setDisableOrbitControls();
                    setSelectedSubjectsUids?.([props.uid]);
                }
            },
            onDrag: ({buttons, offset: [x, y]}) => {
                if (buttons === 1) {
                    setSpring({position: [x, y, 0]});
                }
            },
            onDragEnd: (state) => {
                setEnableOrbitControls();

                writeElementPositionDebounced(position.x, position.y);
            },
            onAbort: (state) => {
                setEnableOrbitControls();
            },
        },
        {
            transform: ([x, y]) => {
                function getSceneMousePosition(clientX: number, clientY: number): Vector3 {
                    const {mouseX, mouseY} = getRelativeMousePosition(gl.domElement, clientX, clientY);

                    const sceneMousePosition = new Vector3();

                    sceneMousePosition.set(mouseX, mouseY, 0).unproject(camera);
                    return sceneMousePosition;
                }

                const sceneMousePosition = getSceneMousePosition(x, y);

                return [sceneMousePosition.x, sceneMousePosition.y];
            },
            drag: {
                filterTaps: true,
                useTouch: true,
            },
            enabled: props.dragable,
        },
    );
    
    return (
            <animated.group
                {...(bind() as any)}
                {...(spring as any)}
            >
               // bunch of ThreeJS objects in here
            </animated.group>
        );
   
```

**Sandbox or Video**
https://www.loom.com/share/a13f14b78330479495f82f95327e08b8

**Information:**
 - React Use Gesture version: 9.1.3
 - Device: Mac Mini M1
 - OS: OSX
 - Browser: Chrome

**Checklist:**
  - [X] I've read the [documentation](https://use-gesture.netlify.app/).
  - [NA] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment] 2021-07-14 07:43
Hey, can you try upgrading to latest beta of `@use-gesture/react` see if this works by any chance?

**Comment by natarius** [comment] 2021-07-14 17:29
This one?

"@use-gesture/react": "^10.0.0-beta.21",

**Comment by dbismut** [comment] 2021-07-14 17:46
Yes.

**Comment by natarius** [comment] 2021-07-15 17:58
now it doesnt work at all

https://www.loom.com/share/978ac7203139448487c1cfb5e1d94910

**Comment by dbismut** [comment] 2021-07-16 07:57
@natarius thanks for the videos. I can try to help you with this, but ideally you would be able to share a minimal sandbox. Can you provide this?

**Comment by feketegy** [comment] 2021-07-19 07:19
This is also happening for me, but I can't put my finger on why it does that, it freezes sometimes inside the bounds as well.

**Comment by vsemk** [comment] 2021-07-19 07:40
Can confirm too. Seems to be only the case with the latest r3f (v7.0.5) though - so maybe an r3f bug?
Possibly related to https://github.com/pmndrs/react-three-fiber/issues/1502 ?

**Comment by natarius** [comment] 2021-07-20 06:33
going back to r3f 7.0.1 fixes the issue for me

**Comment by dbismut** [comment] 2021-07-20 08:13
@joshuaellis @drcmda any ideas where this might come from?

**Comment by drcmda** [comment] 2021-07-20 19:15
and 7.0.2 makes a problem? i went through the commits, there's nothing there:

https://github.com/pmndrs/react-three-fiber/commit/e356872b43d8eb182d497a98be798c8517a53366
https://github.com/pmndrs/react-three-fiber/commit/2d5d157c902e6c4a92ffe7671c1a09ed501f3d1c
https://github.com/pmndrs/react-three-fiber/commit/feca5ea320cc32f7c902bc71aa1a1acad66ecbdc

**Comment by drcmda** [comment] 2021-07-20 19:27
> Can confirm too. Seems to be only the case with the latest r3f (v7.0.5) though - so maybe an r3f bug?
> Possibly related to [pmndrs/react-three-fiber#1502](https://github.com/pmndrs/react-three-fiber/issues/1502) ?

so this does not happen in 7.0.4? are you 100% sure? i think the pointerout issue is unrelated. im getting that even in 6.0.0 so it must be an ancient bugs that's still unfixed.

**Comment by vsemk** [comment] 2021-07-20 19:34
> so this does not happen in 7.0.4? are you 100% sure? that would be really odd, i think 0.5 just added an extra state field "controls" into the state-model. i think the pointerout issue is unrelated. im getting that even in 6.0.0 so it must be an ancient bugs that's still unfixed.

sorry, to be precise indeed the bug is reproducible in both 7.0.4 and 7.0.5. you can reproduce it here https://codesandbox.io/s/bezier-curves-nodes-3k4g6 by setting r3f at these versions

**Comment by drcmda** [comment] 2021-07-20 21:57
it's between 7.0.3 and 7.0.4. there were two prs, one adds forwardref to canvas and one adds attachFns. how in the world does that break events. must debug a little ... :-S

**Comment by drcmda** [comment] 2021-07-20 22:38
should be fixed. turns out this was, somehow, babels fault. it transpiled something into faulty es5 code.

**Comment by dbismut** [comment] 2021-07-22 11:55
Closing this, I'll reopen if the issue persists.

**Closed by dbismut** 2021-07-22 11:55 UTC
Labels: r3f

**Comment by natarius** [comment] 2021-07-22 22:47
Which version includes the fix?

**Comment by dbismut** [comment] 2021-07-23 06:28
@natarius @react-three/fiber v7.0.6
