### ISSUE TITLE
touch event after onDrag is not triggered if done fast enough

### ISSUE THREAD

**Issue by Kryword** [pmndrs/use-gesture#384] opened 2021-11-04 12:29 UTC
**Describe the bug**
If there's a drag event and just after that we try to tap on an element(part of the drag event), it will not register the tap as a click. This works fine on desktop but not on touch mode. In desktop after swiping it will allow you to click and detects the click instantly, while on touch mode it doesn't, it is required a double click, or waiting somewhere around 300-1000 ms(couldn't find out the exact amount).

This bug is reproducible in Chrome(in touch mode), but not in Mozilla.

**Sandbox or Video**
Reproducer: https://codesandbox.io/s/gallant-star-vd18m?file=/src/App.tsx
It is based on an example provided in use-gesture webpage.

Video showing it:
https://user-images.githubusercontent.com/5376070/140312385-513354e2-2272-443b-86ba-235644e7170e.mp4
Notice: Just after swiping I try to click, but it doesn't register it. If I do double tap after swiping, it works fine. I'm using touch mode, normal desktop clicks don't have this issue.

**Information:**
 - React Use Gesture version: Latest: 10.1.2
 - Device: Chrome on PC in touch mode
 - OS: Ubuntu 20.04 LTS
 - Browser: Chrome latest version (this seems to not be reproducible in Mozilla)

I would also like to add this other link with a fix to this issue in chrome that may be worth checking: https://forum.katalon.com/t/missed-events-in-chrome/13463

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment] 2021-11-04 12:47
The `onClick` handler is not part of the API, it's just passed to `bind` as is. You should experience the same behavior if you had done:

```jsx
<animated.div
  className={styles.page}
  {...bind()}
  onClick={() => console.log('ON CLICK HAS BEEN EXECUTED')}
  key={I}
  style={{ display, x }} />
```

In other words, what you're observing shouldn't be dependent on the lib implementation.

**Comment by Kryword** [comment] 2021-11-04 13:11
Interesting, main problem we're seeing is that the onDrag event is executed when we do the click just after swipe(with props.tap set to true, which is correct), but there's no onClick event after that propagated. Somewhere after the onDrag the event is lost, we're not sure if it is from useGesture, React or Chrome itself.

When doing the tap without swiping, the onDrag event is executed with the same information, but the onClick event is not lost, it is only lost if we swipe and tap just after. If we swipe, wait ~300+ms the click works fine. I'm sure is not related with touch-action: none, as we have that set as so on all necessary elements.

I attach another video showing what I'm referring regarding onDrag being called with tap but onClick completely lost:

https://user-images.githubusercontent.com/5376070/140318836-038edbc7-1239-451f-96f7-28e789ea494d.mp4

What we saw is that there should be a touchEnd event which something is capturing and not executing. We looked into the code of useGesture but we didn't found what could be causing it, so it may as well be from some other dependant library.

Is there a way we can detect when the user clicked just after an onDrag event finished?, that would allow us to make a workaround.

**Comment by dbismut** [comment] 2021-11-04 13:31
As you've noted there's the `tap` state property that indicates whether the gesture was a tap, but the logic isn't the same as `onClick`, and requires `{ drag: { filterTaps: true } }` to be passed to the config object.

The difference with `onClick` is that `tap` is `true` when the global displacement is inferior to `3`.

As far as I know, `onClick` is triggered as long as the cursor is released **inside** the target element (no matter how long or how big the displacement is).

Don't know if this helps.

**Comment by Kryword** [comment] 2021-11-04 15:09
Sorry, I did not provide the exact configurations we used in our application for the onDrag function. We did try it also with filterTaps and had the same result, not getting the onClick event triggered. With the cursor inside the target element.

It is only triggered if we wait after doing a swipe some time, if trying to click inmediately(less than ~300ms) it's not executing it, from responsiveness is a big problem in our case. I'll try to improve the reproducer to show the case and the problem better.

And thanks a lot for the very fast answers!

**Comment by dbismut** [comment] 2021-11-04 16:30
Hm. I think it would be worth trying with a very minimal useDrag hook such as this one https://codesandbox.io/s/eloquent-goldwasser-tt17y

And try adding the `onClick` handler as a react prop. 

Lmk if you can reproduce the same behavior.

PS: also, does the issue persist in both iOS and Android devices?

**Comment by Kryword** [comment] 2021-11-15 17:39
Hello, sorry for the delay. I've prepared a reproducer using the provided minimal useDrag hook:
https://codesandbox.io/s/rough-feather-vl2h3?file=/src/App.js

It seems the click is only lost if we have set `touch-action: none` in css on the draggable element. If touch-action is not set, it will work fine and the clicks are not captured/removed. Not sure how it could be fixed from the library side. I've spent plenty time looking into how this works, but I did not find yet why this happens when `touch-action` is set to `none`, will keep looking.

Any feedback is welcome, thanks for all your time.

**Comment by dbismut** [comment] 2021-11-17 08:00
@Kryword I really can't reproduce I'm sorry. Based from the minimal hook, you can see that there's hardly any reason why it would have any impact on how the `onClick` handler behaves. I'm going to close this now, but feel free to comment in this thread.

**Closed by dbismut** 2021-11-17 08:00 UTC

**Comment by Kryword** [comment] 2021-11-17 09:39
Hello, no problem, thanks to your minimal hook, the reproducer will be useful for fixing it in the end. We found out indeed it is a chrome bug, not yet fixed. For more information: https://bugs.chromium.org/p/chromium/issues/detail?id=1141207&q=%22touch-action%22&can=2

We'll report this to them with the extra information and the reproducer and we hope they can tackle it. Thanks a lot for your help and fast responses! :+1:
