### ISSUE TITLE
`touch-action: pan-y` does not always help to avoid scrolling on iOS

### ISSUE THREAD

**Issue by seleckis** [pmndrs/use-gesture#304] opened 2021-05-21 17:29 UTC
**Describe the bug**
When swiping very precisely it works great: the item is draggable and the page is not scrolling in the same time. But when I swipe roughly (like most users do) or in almost diagonal direction, then it seems it starts dragging and then page scrolling gesture takes control: the draggable element stops dragging, and the page starts scrolling.

Reproduces only on iPhone. Android/Chrome works great.

**Sandbox or Video**
Couldn't make it properly work in my project first, but then I tried the official documentation and got the same result: https://use-gesture.netlify.app/docs/extras/
Please check this video: https://user-images.githubusercontent.com/988504/119175613-b3c4f680-ba72-11eb-9a8a-4725279b1861.mp4 

**Information:**
 - React Use Gesture version: 9.1.3 and which is used on official documentation
 - Device: iPhone11
 - OS: iOS14.4.2
 - Browser: Safari

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment] 2021-05-21 18:18
Just to clarify: `use-gesture` isn't responsible for how `pan-y` behaves.

I understand where that glitch comes from though, and the problem is that the way a browser detects user-intent is a lot more sophisticated than use-gesture's, so there can be some conflicts indeed. Here's what happens in details in the doc example, that has the `axis` option set to `x`:

1. User starts dragging diagonally.
2. use-gesture thinks it's a horizontal drag and the component starts to drag.
3. Browser thinks that eventually it's a scroll, and cancels the pointer event, therefore the drag, and hence the glitch.

There's a few way you can tackle this:

- try increasing the threshold so that use-gesture detects the drag: in the docs, the `threshold` is set to `20`. If you set it to `100` you'll probably never get the glitch, but that comes to the expense of the user experience (as the UI might seem unresponsive).
- use body-scroll-lock or equivalent (I actually prefer [tua-body-scroll-lock](https://github.com/tuateam/tua-body-scroll-lock), so that as soon as use-gesture detects a horizontal drag, you imperatively disable the browser lock. That should work in most cases.
-  use `target`, `pointer.touch: true` and `eventOptions.passive: false` to be able to `preventDefault()` yourself. If it fails, the drag will persist but you won't have the glitch.

Not an easy one unfortunately. I'm tempted to close this unless you have a better proposal?

**Comment by seleckis** [comment] 2021-05-21 20:21
Thank you, I will try your solutions.

In this case, we could talk about misunderstanding in docs. In [this article](https://use-gesture.netlify.app/docs/extras/) by the phrase "But there is a simpler, more effective solution, which has to do with a simple CSS property." seems the `touch-action: pan-y` is a complete solution for this issue, but this is not true. Ok, there is a note that it can fail, but should work in most situations. Should it be regarded that those minor situations happens only in iOS? But it completely fails on iOS, I don't think it is a good reason to call it "most situations".

**Comment by dbismut** [comment] 2021-05-21 20:30
It doesn't completely fail on iOS, not sure what you mean by that.

**Comment by seleckis** [comment] 2021-05-21 20:36
Have you seen my video? I cannot call it, like "in most cases work". :) Maybe it is worth to add more information about this issue in documentation with appropriate examples?

**Comment by dbismut** [comment] 2021-05-22 06:03
Yes I've seen your video, but the issue is that I don't see your finger so it's hard to figure out whether you were dramatically exaggerating a "wrong" horizontal swipe: for mobile it's important that I see the interaction to understand what happens. This usually requires two phones, or possibly assistive touch turned on, or using the xCode simulator. 

But anyways, when I saying that it works in most situations, I'm not saying that you can't reproduce the issue systematically: I know how to trigger the glitch and if I want to I can make it look bad all the time. The question is: how does the average user swipe, and until now I didn't have complaints ;)

But bottom line yes, I agree that the docs should be a bit more precise on that front. 

Did you try the sandbox I sent?

**Comment by seleckis** [comment] 2021-05-24 10:33
@dbismut I have just checked your sandbox in iOS Simulator, scrolling is always working. Take a look at the video: 

https://user-images.githubusercontent.com/988504/119335123-98393600-bc94-11eb-934a-63abd162481a.mp4

**Comment by dbismut** [comment] 2021-05-24 10:44
Try the actual sandbox, not iframed. https://xntdm.csb.app

**Comment by seleckis** [comment] 2021-05-24 12:17
Yes, works much better. But I cannot figure out how to make it work in my app. Is ref assignment available only in v10 beta? I use react-use-gestures v9.1.3 and useDrug with ref is not firing any event.

**Comment by dbismut** [comment] 2021-05-24 13:09
You can try using v10 it's really close to prod and fixes v9 bugs. If not, v9 uses `domTarget` instead of `target`.

**Closed** 2021-05-25 15:19 UTC
